### ISSUE TITLE
error when downloading more than one track on an album

### ISSUE THREAD

**Issue by losbe** [jsavargas/zspotify#167] opened 2023-12-24 13:22 UTC
I receive this error, the first track downloads it but the second sends this error. I have already tried several albums and it is not a region problem.
![Screenshot_20231224-092036_Termux](https://github.com/jsavargas/zspotify/assets/78452250/6404e128-4500-4a11-896d-8a9cc14d6c19)

Setting audiotags 1. Corazón Sin Cara
Traceback (most recent call last):
  File "/data/data/com.termux/files/usr/lib/python3.11/site-packages/mutagen/ogg.py", line 90, in __init__
    crc, segments) = struct.unpack("<4sBBqIIiB", header)
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
struct.error: unpack requires a buffer of 27 bytes

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/data/data/com.termux/files/usr/lib/python3.11/site-packages/mutagen/ogg.py", line 589, in save
    self.tags._inject(filething.fileobj, padding)
  File "/data/data/com.termux/files/usr/lib/python3.11/site-packages/mutagen/oggvorbis.py", line 146, in _inject
    OggPage.replace(fileobj, old_pages, new_pages)
  File "/data/data/com.termux/files/usr/lib/python3.11/site-packages/mutagen/ogg.py", line 438, in replace
    cls.renumber(fileobj, serial, sequence)
  File "/data/data/com.termux/files/usr/lib/python3.11/site-packages/mutagen/ogg.py", line 230, in renumber
    page = OggPage(fileobj)
           ^^^^^^^^^^^^^^^^
  File "/data/data/com.termux/files/usr/lib/python3.11/site-packages/mutagen/ogg.py", line 92, in __init__
    raise error("unable to read full header; got %r" % header)
mutagen.ogg.error: unable to read full header; got b'\x00\x00'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/data/data/com.termux/files/usr/bin/zspotify", line 8, in <module>
    sys.exit(main())
             ^^^^^^
  File "/data/data/com.termux/files/usr/lib/python3.11/site-packages/zspotify/__main__.py", line 697, in main
    zs.start()
  File "/data/data/com.termux/files/usr/lib/python3.11/site-packages/zspotify/__main__.py", line 641, in start
    self.download_by_url(album)
  File "/data/data/com.termux/files/usr/lib/python3.11/site-packages/zspotify/__main__.py", line 508, in download_by_url
    ret = self.download_album(parsed_url["album"])
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/data/data/com.termux/files/usr/lib/python3.11/site-packages/zspotify/__main__.py", line 469, in download_album
    self.download_track(song["id"], newBasePath, "album")
  File "/data/data/com.termux/files/usr/lib/python3.11/site-packages/zspotify/__main__.py", line 348, in download_track
    self.tagger.set_audio_tags(
  File "/data/data/com.termux/files/usr/lib/python3.11/site-packages/zspotify/tagger.py", line 22, in set_audio_tags
    self._set_other_tags(fullpath, artists, name, album_name, release_year, disc_number,
  File "/data/data/com.termux/files/usr/lib/python3.11/site-packages/zspotify/tagger.py", line 75, in _set_other_tags
    tags.save()
  File "/data/data/com.termux/files/usr/lib/python3.11/site-packages/music_tag/file.py", line 374, in save
    self.mfile.save(**kwargs)
  File "/data/data/com.termux/files/usr/lib/python3.11/site-packages/mutagen/_util.py", line 156, in wrapper
    return func(self, h, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/data/data/com.termux/files/usr/lib/python3.11/site-packages/mutagen/ogg.py", line 591, in save
    reraise(self._Error, e, sys.exc_info()[2])
  File "/data/data/com.termux/files/usr/lib/python3.11/site-packages/mutagen/_util.py", line 43, in reraise
    raise tp(value).with_traceback(tb)
  File "/data/data/com.termux/files/usr/lib/python3.11/site-packages/mutagen/ogg.py", line 589, in save
    self.tags._inject(filething.fileobj, padding)
  File "/data/data/com.termux/files/usr/lib/python3.11/site-packages/mutagen/oggvorbis.py", line 146, in _inject
    OggPage.replace(fileobj, old_pages, new_pages)
  File "/data/data/com.termux/files/usr/lib/python3.11/site-packages/mutagen/ogg.py", line 438, in replace
    cls.renumber(fileobj, serial, sequence)
  File "/data/data/com.termux/files/usr/lib/python3.11/site-packages/mutagen/ogg.py", line 230, in renumber
    page = OggPage(fileobj)
           ^^^^^^^^^^^^^^^^
  File "/data/data/com.termux/files/usr/lib/python3.11/site-packages/mutagen/ogg.py", line 92, in __init__
    raise error("unable to read full header; got %r" % header)
mutagen.oggvorbis.OggVorbisHeaderError: unable to read full header; got b'\x00\x00'

**Comment by niclimcy** [comment] 2023-12-29 19:19
Duplicate of #161

**Closed** 2023-12-29 19:19 UTC
Labels: bug
